
/* DO NOT EDIT! This is an autogenerated file. See scripts/buildcommands.py. */

#include "board/irq.h"
#include "board/pgm.h"
#include "command.h"
#include "compiler.h"
#include "initial_pins.h"

void
ctr_run_initfuncs(void)
{
    extern void alloc_init(void);
    alloc_init();
    extern void initial_pins_setup(void);
    initial_pins_setup();
    extern void timer_init(void);
    timer_init();
}

void
ctr_run_shutdownfuncs(void)
{
    extern void sendf_shutdown(void);
    sendf_shutdown();
    extern void move_reset(void);
    move_reset();
    extern void digital_out_shutdown(void);
    digital_out_shutdown();
    extern void stepper_shutdown(void);
    stepper_shutdown();
    extern void trsync_shutdown(void);
    trsync_shutdown();
    extern void analog_in_shutdown(void);
    analog_in_shutdown();
    extern void spidev_shutdown(void);
    spidev_shutdown();
    extern void pwm_shutdown(void);
    pwm_shutdown();
    extern void tmcuart_shutdown(void);
    tmcuart_shutdown();
    extern void st7920_shutdown(void);
    st7920_shutdown();
    extern void hd44780_shutdown(void);
    hd44780_shutdown();
    extern void pca9685_shutdown(void);
    pca9685_shutdown();
}

void
ctr_run_taskfuncs(void)
{
    irq_poll();
    extern void trsync_task(void);
    trsync_task();
    irq_poll();
    extern void analog_in_task(void);
    analog_in_task();
    irq_poll();
    extern void buttons_task(void);
    buttons_task();
    irq_poll();
    extern void tmcuart_task(void);
    tmcuart_task();
    irq_poll();
    extern void counter_task(void);
    counter_task();
    irq_poll();
    extern void thermocouple_task(void);
    thermocouple_task();
    irq_poll();
    extern void adxl345_task(void);
    adxl345_task();
    irq_poll();
    extern void spi_angle_task(void);
    spi_angle_task();
    irq_poll();
    extern void mpu9250_task(void);
    mpu9250_task();
    irq_poll();
    extern void lis2dw_task(void);
    lis2dw_task();
    irq_poll();
    extern void ldc1612_task(void);
    ldc1612_task();
    irq_poll();
    extern void console_task(void);
    console_task();
    irq_poll();
    extern void watchdog_task(void);
    watchdog_task();
    irq_poll();
    extern void ds18_task(void);
    ds18_task();
    irq_poll();
}

uint8_t __always_inline
ctr_lookup_static_string(const char *str)
{
    if (__builtin_strcmp(str, "Shutdown cleared when not shutdown") == 0)
        return 2;
    if (__builtin_strcmp(str, "Timer too close") == 0)
        return 3;
    if (__builtin_strcmp(str, "sentinel timer called") == 0)
        return 4;
    if (__builtin_strcmp(str, "Invalid command") == 0)
        return 5;
    if (__builtin_strcmp(str, "Message encode error") == 0)
        return 6;
    if (__builtin_strcmp(str, "Command parser error") == 0)
        return 7;
    if (__builtin_strcmp(str, "Command request") == 0)
        return 8;
    if (__builtin_strcmp(str, "config_reset only available when shutdown") == 0)
        return 9;
    if (__builtin_strcmp(str, "oids already allocated") == 0)
        return 10;
    if (__builtin_strcmp(str, "Can't assign oid") == 0)
        return 11;
    if (__builtin_strcmp(str, "Invalid oid type") == 0)
        return 12;
    if (__builtin_strcmp(str, "Already finalized") == 0)
        return 13;
    if (__builtin_strcmp(str, "Invalid move request size") == 0)
        return 14;
    if (__builtin_strcmp(str, "Move queue overflow") == 0)
        return 15;
    if (__builtin_strcmp(str, "alloc_chunks failed") == 0)
        return 16;
    if (__builtin_strcmp(str, "alloc_chunk failed") == 0)
        return 17;
    if (__builtin_strcmp(str, "update_digital_out not valid with active queue") == 0)
        return 18;
    if (__builtin_strcmp(str, "Scheduled digital out event will exceed max_duration") == 0)
        return 19;
    if (__builtin_strcmp(str, "Can not set soft pwm cycle ticks while updates pending") == 0)
        return 20;
    if (__builtin_strcmp(str, "Missed scheduling of next digital out event") == 0)
        return 21;
    if (__builtin_strcmp(str, "Can't reset time when stepper active") == 0)
        return 22;
    if (__builtin_strcmp(str, "Invalid count parameter") == 0)
        return 23;
    if (__builtin_strcmp(str, "Stepper too far in past") == 0)
        return 24;
    if (__builtin_strcmp(str, "Can't add signal that is already active") == 0)
        return 25;
    if (__builtin_strcmp(str, "ADC out of range") == 0)
        return 26;
    if (__builtin_strcmp(str, "Invalid spi config") == 0)
        return 27;
    if (__builtin_strcmp(str, "i2c_modify_bits: Odd number of bits!") == 0)
        return 28;
    if (__builtin_strcmp(str, "Scheduled pwm event will exceed max_duration") == 0)
        return 29;
    if (__builtin_strcmp(str, "Missed scheduling of next hard pwm event") == 0)
        return 30;
    if (__builtin_strcmp(str, "Invalid buttons retransmit count") == 0)
        return 31;
    if (__builtin_strcmp(str, "Set button past maximum button count") == 0)
        return 32;
    if (__builtin_strcmp(str, "Max of 8 buttons") == 0)
        return 33;
    if (__builtin_strcmp(str, "tmcuart data too large") == 0)
        return 34;
    if (__builtin_strcmp(str, "Invalid neopixel update command") == 0)
        return 35;
    if (__builtin_strcmp(str, "Invalid neopixel data_size") == 0)
        return 36;
    if (__builtin_strcmp(str, "soft_i2c NACK") == 0)
        return 37;
    if (__builtin_strcmp(str, "Thermocouple reader fault") == 0)
        return 38;
    if (__builtin_strcmp(str, "Invalid thermocouple chip type") == 0)
        return 39;
    if (__builtin_strcmp(str, "angle sensor requires cs pin") == 0)
        return 40;
    if (__builtin_strcmp(str, "Invalid spi_angle chip type") == 0)
        return 41;
    if (__builtin_strcmp(str, "Rescheduled timer in the past") == 0)
        return 42;
    if (__builtin_strcmp(str, "Force shutdown command") == 0)
        return 43;
    if (__builtin_strcmp(str, "Invalid pca9685 channel or value") == 0)
        return 44;
    if (__builtin_strcmp(str, "Scheduled pca9685 event will exceed max_duration") == 0)
        return 45;
    if (__builtin_strcmp(str, "Invalid pca9685 value") == 0)
        return 46;
    if (__builtin_strcmp(str, "Missed scheduling of next pca9685 event") == 0)
        return 47;
    if (__builtin_strcmp(str, "Unable to open and init PCA9685 device") == 0)
        return 48;
    if (__builtin_strcmp(str, "Too many i2c devices") == 0)
        return 49;
    if (__builtin_strcmp(str, "All PCA9685 channels must have the same cycle_ticks") == 0)
        return 50;
    if (__builtin_strcmp(str, "Unable to update PCA9685 value") == 0)
        return 51;
    if (__builtin_strcmp(str, "Unable to write to spi") == 0)
        return 52;
    if (__builtin_strcmp(str, "Unable to issue spi ioctl") == 0)
        return 53;
    if (__builtin_strcmp(str, "Unable to set SPI mode") == 0)
        return 54;
    if (__builtin_strcmp(str, "Unable to set SPI speed") == 0)
        return 55;
    if (__builtin_strcmp(str, "Unable to set non-blocking on spi device") == 0)
        return 56;
    if (__builtin_strcmp(str, "Unable to open spi device") == 0)
        return 57;
    if (__builtin_strcmp(str, "Too many spi devices") == 0)
        return 58;
    if (__builtin_strcmp(str, "Error on analog read") == 0)
        return 59;
    if (__builtin_strcmp(str, "Unable to open adc device") == 0)
        return 60;
    if (__builtin_strcmp(str, "Unable to config pwm device") == 0)
        return 61;
    if (__builtin_strcmp(str, "Unable to read i2c device") == 0)
        return 62;
    if (__builtin_strcmp(str, "Unable write i2c device") == 0)
        return 63;
    if (__builtin_strcmp(str, "Unable to open i2c device") == 0)
        return 64;
    if (__builtin_strcmp(str, "Unable to open in GPIO chip line") == 0)
        return 65;
    if (__builtin_strcmp(str, "Unable to open out GPIO chip line") == 0)
        return 66;
    if (__builtin_strcmp(str, "Unable to open GPIO chip device") == 0)
        return 67;
    if (__builtin_strcmp(str, "GPIO chip device not found") == 0)
        return 68;
    if (__builtin_strcmp(str, "DS18B20 sensor didn't respond in time") == 0)
        return 69;
    if (__builtin_strcmp(str, "DS18B20 out of range") == 0)
        return 70;
    if (__builtin_strcmp(str, "Error reading DS18B20 sensor") == 0)
        return 71;
    if (__builtin_strcmp(str, "Error getting monotonic clock time") == 0)
        return 72;
    if (__builtin_strcmp(str, "Could not start DS18B20 reader thread") == 0)
        return 73;
    if (__builtin_strcmp(str, "Could not start DS18B20 reader thread (cond init)") == 0)
        return 74;
    if (__builtin_strcmp(str, "Could not start DS18B20 reader thread (mutex init)") == 0)
        return 75;
    if (__builtin_strcmp(str, "Invalid DS18B20 serial id, could not open for reading") == 0)
        return 76;
    if (__builtin_strcmp(str, "Invalid DS18B20 serial id, must not contain '/'") == 0)
        return 77;
    return 0xff;
}

const struct initial_pin_s initial_pins[] PROGMEM = {
};
const int initial_pins_size PROGMEM = ARRAY_SIZE(initial_pins);

static const uint8_t command_parameters0[] PROGMEM = {
    PT_uint16 };
static const uint8_t command_parameters1[] PROGMEM = {
    PT_uint32, PT_uint16 };
static const uint8_t command_parameters2[] PROGMEM = {
    PT_uint32, PT_progmem_buffer };
static const uint8_t command_parameters3[] PROGMEM = {
    PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters4[] PROGMEM = {
    PT_uint32, PT_uint32 };
static const uint8_t command_parameters5[] PROGMEM = {
    PT_uint32 };
static const uint8_t command_parameters6[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_uint16 };
static const uint8_t command_parameters7[] PROGMEM = {
    PT_buffer };
static const uint8_t command_parameters8[] PROGMEM = {
    PT_byte, PT_int32 };
static const uint8_t command_parameters9[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32, PT_byte };
static const uint8_t command_parameters10[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters11[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16 };
static const uint8_t command_parameters12[] PROGMEM = {
    PT_byte, PT_buffer };
static const uint8_t command_parameters13[] PROGMEM = {
    PT_byte, PT_byte, PT_buffer };
static const uint8_t command_parameters14[] PROGMEM = {
    PT_byte, PT_byte };
static const uint8_t command_parameters15[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters16[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte };
static const uint8_t command_parameters17[] PROGMEM = {
    PT_byte, PT_uint32, PT_buffer };
static const uint8_t command_parameters18[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters19[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_uint32, PT_uint16 };
static const uint8_t command_parameters20[] PROGMEM = {
    PT_byte, PT_uint16, PT_buffer };
static const uint8_t command_parameters21[] PROGMEM = {
    PT_byte, PT_uint32, PT_int32, PT_uint32 };
static const uint8_t command_parameters22[] PROGMEM = {
    PT_uint32, PT_byte };
static const uint8_t command_parameters23[] PROGMEM = {
    PT_byte };
static const uint8_t command_parameters24[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters25[] PROGMEM = {
    PT_byte, PT_uint32 };
static const uint8_t command_parameters26[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters27[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_int16 };
static const uint8_t command_parameters28[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters29[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_uint32, PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters30[] PROGMEM = {
    PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters31[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_uint32, PT_uint16, PT_uint16, PT_byte };
static const uint8_t command_parameters32[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte };
static const uint8_t command_parameters33[] PROGMEM = {
    PT_byte, PT_buffer, PT_buffer };
static const uint8_t command_parameters34[] PROGMEM = {
    PT_byte, PT_buffer, PT_uint32 };
static const uint8_t command_parameters35[] PROGMEM = {
    PT_uint32, PT_uint32, PT_uint16 };
static const uint8_t command_parameters36[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_uint16, PT_uint32 };
static const uint8_t command_parameters37[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_byte };
static const uint8_t command_parameters38[] PROGMEM = {
    PT_byte, PT_buffer, PT_byte };
static const uint8_t command_parameters39[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters40[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_uint32, PT_uint32 };
static const uint8_t command_parameters41[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters42[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters43[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters44[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_byte };
static const uint8_t command_parameters45[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters46[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_uint32, PT_uint16 };
static const uint8_t command_parameters47[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte, PT_uint32, PT_uint16, PT_uint16, PT_uint32 };
static const uint8_t command_parameters48[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_int32, PT_int32 };

const struct command_encoder command_encoder_92 PROGMEM = {    
    // starting
    .encoded_msgid=92, // msgid=92
    .num_params=0,
    .param_types = 0,
    .max_size=6,
};
const struct command_encoder command_encoder_93 PROGMEM = {    
    // is_shutdown static_string_id=%hu
    .encoded_msgid=93, // msgid=93
    .num_params=1,
    .param_types = command_parameters0,
    .max_size=9,
};
const struct command_encoder command_encoder_94 PROGMEM = {    
    // shutdown clock=%u static_string_id=%hu
    .encoded_msgid=94, // msgid=94
    .num_params=2,
    .param_types = command_parameters1,
    .max_size=14,
};
const struct command_encoder command_encoder_0 PROGMEM = {    
    // identify_response offset=%u data=%.*s
    .encoded_msgid=0, // msgid=0
    .num_params=2,
    .param_types = command_parameters2,
    .max_size=64,
};
const struct command_encoder command_encoder_95 PROGMEM = {    
    // stats count=%u sum=%u sumsq=%u
    .encoded_msgid=95, // msgid=95
    .num_params=3,
    .param_types = command_parameters3,
    .max_size=21,
};
const struct command_encoder command_encoder_96 PROGMEM = {    
    // uptime high=%u clock=%u
    .encoded_msgid=96, // msgid=-32
    .num_params=2,
    .param_types = command_parameters4,
    .max_size=16,
};
const struct command_encoder command_encoder_97 PROGMEM = {    
    // clock clock=%u
    .encoded_msgid=97, // msgid=-31
    .num_params=1,
    .param_types = command_parameters5,
    .max_size=11,
};
const struct command_encoder command_encoder_98 PROGMEM = {    
    // config is_config=%c crc=%u is_shutdown=%c move_count=%hu
    .encoded_msgid=98, // msgid=-30
    .num_params=4,
    .param_types = command_parameters6,
    .max_size=18,
};
const struct command_encoder command_encoder_99 PROGMEM = {    
    // pong data=%*s
    .encoded_msgid=99, // msgid=-29
    .num_params=1,
    .param_types = command_parameters7,
    .max_size=64,
};
const struct command_encoder command_encoder_100 PROGMEM = {    
    // debug_result val=%u
    .encoded_msgid=100, // msgid=-28
    .num_params=1,
    .param_types = command_parameters5,
    .max_size=11,
};
const struct command_encoder command_encoder_101 PROGMEM = {    
    // stepper_position oid=%c pos=%i
    .encoded_msgid=101, // msgid=-27
    .num_params=2,
    .param_types = command_parameters8,
    .max_size=13,
};
const struct command_encoder command_encoder_102 PROGMEM = {    
    // endstop_state oid=%c homing=%c next_clock=%u pin_value=%c
    .encoded_msgid=102, // msgid=-26
    .num_params=4,
    .param_types = command_parameters9,
    .max_size=17,
};
const struct command_encoder command_encoder_103 PROGMEM = {    
    // trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u
    .encoded_msgid=103, // msgid=-25
    .num_params=4,
    .param_types = command_parameters10,
    .max_size=17,
};
const struct command_encoder command_encoder_104 PROGMEM = {    
    // analog_in_state oid=%c next_clock=%u value=%hu
    .encoded_msgid=104, // msgid=-24
    .num_params=3,
    .param_types = command_parameters11,
    .max_size=16,
};
const struct command_encoder command_encoder_105 PROGMEM = {    
    // spi_transfer_response oid=%c response=%*s
    .encoded_msgid=105, // msgid=-23
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_106 PROGMEM = {    
    // i2c_read_response oid=%c response=%*s
    .encoded_msgid=106, // msgid=-22
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_107 PROGMEM = {    
    // buttons_state oid=%c ack_count=%c state=%*s
    .encoded_msgid=107, // msgid=-21
    .num_params=3,
    .param_types = command_parameters13,
    .max_size=64,
};
const struct command_encoder command_encoder_108 PROGMEM = {    
    // tmcuart_response oid=%c read=%*s
    .encoded_msgid=108, // msgid=-20
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_109 PROGMEM = {    
    // neopixel_result oid=%c success=%c
    .encoded_msgid=109, // msgid=-19
    .num_params=2,
    .param_types = command_parameters14,
    .max_size=10,
};
const struct command_encoder command_encoder_110 PROGMEM = {    
    // counter_state oid=%c next_clock=%u count=%u count_clock=%u
    .encoded_msgid=110, // msgid=-18
    .num_params=4,
    .param_types = command_parameters15,
    .max_size=23,
};
const struct command_encoder command_encoder_111 PROGMEM = {    
    // thermocouple_result oid=%c next_clock=%u value=%u fault=%c
    .encoded_msgid=111, // msgid=-17
    .num_params=4,
    .param_types = command_parameters16,
    .max_size=20,
};
const struct command_encoder command_encoder_112 PROGMEM = {    
    // spi_angle_transfer_response oid=%c clock=%u response=%*s
    .encoded_msgid=112, // msgid=-16
    .num_params=3,
    .param_types = command_parameters17,
    .max_size=64,
};
const struct command_encoder command_encoder_113 PROGMEM = {    
    // ldc1612_home_state oid=%c homing=%c trigger_clock=%u
    .encoded_msgid=113, // msgid=-15
    .num_params=3,
    .param_types = command_parameters18,
    .max_size=15,
};
const struct command_encoder command_encoder_114 PROGMEM = {    
    // sensor_bulk_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%u possible_overflows=%hu
    .encoded_msgid=114, // msgid=-14
    .num_params=6,
    .param_types = command_parameters19,
    .max_size=29,
};
const struct command_encoder command_encoder_115 PROGMEM = {    
    // sensor_bulk_data oid=%c sequence=%hu data=%*s
    .encoded_msgid=115, // msgid=-13
    .num_params=3,
    .param_types = command_parameters20,
    .max_size=64,
};
const struct command_encoder command_encoder_116 PROGMEM = {    
    // ds18b20_result oid=%c next_clock=%u value=%i fault=%u
    .encoded_msgid=116, // msgid=-12
    .num_params=4,
    .param_types = command_parameters21,
    .max_size=23,
};

const __always_inline struct command_encoder *
ctr_lookup_encoder(const char *str)
{
    if (__builtin_strcmp(str, "starting") == 0)
        return &command_encoder_92;
    if (__builtin_strcmp(str, "is_shutdown static_string_id=%hu") == 0)
        return &command_encoder_93;
    if (__builtin_strcmp(str, "shutdown clock=%u static_string_id=%hu") == 0)
        return &command_encoder_94;
    if (__builtin_strcmp(str, "identify_response offset=%u data=%.*s") == 0)
        return &command_encoder_0;
    if (__builtin_strcmp(str, "stats count=%u sum=%u sumsq=%u") == 0)
        return &command_encoder_95;
    if (__builtin_strcmp(str, "uptime high=%u clock=%u") == 0)
        return &command_encoder_96;
    if (__builtin_strcmp(str, "clock clock=%u") == 0)
        return &command_encoder_97;
    if (__builtin_strcmp(str, "config is_config=%c crc=%u is_shutdown=%c move_count=%hu") == 0)
        return &command_encoder_98;
    if (__builtin_strcmp(str, "pong data=%*s") == 0)
        return &command_encoder_99;
    if (__builtin_strcmp(str, "debug_result val=%u") == 0)
        return &command_encoder_100;
    if (__builtin_strcmp(str, "stepper_position oid=%c pos=%i") == 0)
        return &command_encoder_101;
    if (__builtin_strcmp(str, "endstop_state oid=%c homing=%c next_clock=%u pin_value=%c") == 0)
        return &command_encoder_102;
    if (__builtin_strcmp(str, "trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u") == 0)
        return &command_encoder_103;
    if (__builtin_strcmp(str, "analog_in_state oid=%c next_clock=%u value=%hu") == 0)
        return &command_encoder_104;
    if (__builtin_strcmp(str, "spi_transfer_response oid=%c response=%*s") == 0)
        return &command_encoder_105;
    if (__builtin_strcmp(str, "i2c_read_response oid=%c response=%*s") == 0)
        return &command_encoder_106;
    if (__builtin_strcmp(str, "buttons_state oid=%c ack_count=%c state=%*s") == 0)
        return &command_encoder_107;
    if (__builtin_strcmp(str, "tmcuart_response oid=%c read=%*s") == 0)
        return &command_encoder_108;
    if (__builtin_strcmp(str, "neopixel_result oid=%c success=%c") == 0)
        return &command_encoder_109;
    if (__builtin_strcmp(str, "counter_state oid=%c next_clock=%u count=%u count_clock=%u") == 0)
        return &command_encoder_110;
    if (__builtin_strcmp(str, "thermocouple_result oid=%c next_clock=%u value=%u fault=%c") == 0)
        return &command_encoder_111;
    if (__builtin_strcmp(str, "spi_angle_transfer_response oid=%c clock=%u response=%*s") == 0)
        return &command_encoder_112;
    if (__builtin_strcmp(str, "ldc1612_home_state oid=%c homing=%c trigger_clock=%u") == 0)
        return &command_encoder_113;
    if (__builtin_strcmp(str, "sensor_bulk_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%u possible_overflows=%hu") == 0)
        return &command_encoder_114;
    if (__builtin_strcmp(str, "sensor_bulk_data oid=%c sequence=%hu data=%*s") == 0)
        return &command_encoder_115;
    if (__builtin_strcmp(str, "ds18b20_result oid=%c next_clock=%u value=%i fault=%u") == 0)
        return &command_encoder_116;
    return NULL;
}

const __always_inline struct command_encoder *
ctr_lookup_output(const char *str)
{
    
    return NULL;
}

extern void command_allocate_oids(uint32_t*);
extern void command_buttons_ack(uint32_t*);
extern void command_buttons_add(uint32_t*);
extern void command_buttons_query(uint32_t*);
extern void command_clear_shutdown(uint32_t*);
extern void command_config_adxl345(uint32_t*);
extern void command_config_analog_in(uint32_t*);
extern void command_config_buttons(uint32_t*);
extern void command_config_counter(uint32_t*);
extern void command_config_digital_out(uint32_t*);
extern void command_config_ds18b20(uint32_t*);
extern void command_config_endstop(uint32_t*);
extern void command_config_hd44780(uint32_t*);
extern void command_config_i2c(uint32_t*);
extern void command_config_ldc1612(uint32_t*);
extern void command_config_ldc1612_with_intb(uint32_t*);
extern void command_config_lis2dw(uint32_t*);
extern void command_config_mpu9250(uint32_t*);
extern void command_config_neopixel(uint32_t*);
extern void command_config_pca9685(uint32_t*);
extern void command_config_pwm_out(uint32_t*);
extern void command_config_reset(uint32_t*);
extern void command_config_spi(uint32_t*);
extern void command_config_spi_angle(uint32_t*);
extern void command_config_spi_shutdown(uint32_t*);
extern void command_config_spi_without_cs(uint32_t*);
extern void command_config_st7920(uint32_t*);
extern void command_config_stepper(uint32_t*);
extern void command_config_thermocouple(uint32_t*);
extern void command_config_tmcuart(uint32_t*);
extern void command_config_trsync(uint32_t*);
extern void command_debug_nop(uint32_t*);
extern void command_debug_ping(uint32_t*);
extern void command_debug_read(uint32_t*);
extern void command_debug_write(uint32_t*);
extern void command_emergency_stop(uint32_t*);
extern void command_endstop_home(uint32_t*);
extern void command_endstop_query_state(uint32_t*);
extern void command_finalize_config(uint32_t*);
extern void command_get_clock(uint32_t*);
extern void command_get_config(uint32_t*);
extern void command_get_uptime(uint32_t*);
extern void command_hd44780_send_cmds(uint32_t*);
extern void command_hd44780_send_data(uint32_t*);
extern void command_i2c_modify_bits(uint32_t*);
extern void command_i2c_read(uint32_t*);
extern void command_i2c_set_bus(uint32_t*);
extern void command_i2c_set_software_bus(uint32_t*);
extern void command_i2c_write(uint32_t*);
extern void command_identify(uint32_t*);
extern void command_ldc1612_setup_home(uint32_t*);
extern void command_neopixel_send(uint32_t*);
extern void command_neopixel_update(uint32_t*);
extern void command_query_adxl345(uint32_t*);
extern void command_query_adxl345_status(uint32_t*);
extern void command_query_analog_in(uint32_t*);
extern void command_query_counter(uint32_t*);
extern void command_query_ds18b20(uint32_t*);
extern void command_query_ldc1612(uint32_t*);
extern void command_query_ldc1612_home_state(uint32_t*);
extern void command_query_lis2dw(uint32_t*);
extern void command_query_lis2dw_status(uint32_t*);
extern void command_query_mpu9250(uint32_t*);
extern void command_query_mpu9250_status(uint32_t*);
extern void command_query_spi_angle(uint32_t*);
extern void command_query_status_ldc1612(uint32_t*);
extern void command_query_thermocouple(uint32_t*);
extern void command_queue_digital_out(uint32_t*);
extern void command_queue_pca9685_out(uint32_t*);
extern void command_queue_pwm_out(uint32_t*);
extern void command_queue_step(uint32_t*);
extern void command_reset_step_clock(uint32_t*);
extern void command_set_digital_out(uint32_t*);
extern void command_set_digital_out_pwm_cycle(uint32_t*);
extern void command_set_next_step_dir(uint32_t*);
extern void command_set_pca9685_out(uint32_t*);
extern void command_set_pwm_out(uint32_t*);
extern void command_spi_angle_transfer(uint32_t*);
extern void command_spi_send(uint32_t*);
extern void command_spi_set_bus(uint32_t*);
extern void command_spi_set_software_bus(uint32_t*);
extern void command_spi_transfer(uint32_t*);
extern void command_st7920_send_cmds(uint32_t*);
extern void command_st7920_send_data(uint32_t*);
extern void command_stepper_get_position(uint32_t*);
extern void command_stepper_stop_on_trigger(uint32_t*);
extern void command_tmcuart_send(uint32_t*);
extern void command_trsync_set_timeout(uint32_t*);
extern void command_trsync_start(uint32_t*);
extern void command_trsync_trigger(uint32_t*);
extern void command_update_digital_out(uint32_t*);

const struct command_parser command_index[] PROGMEM = {
{
}, {
    // identify offset=%u count=%c
    .encoded_msgid=1, // msgid=1
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0x01,
    .func=command_identify
}, {
    // clear_shutdown
    .encoded_msgid=2, // msgid=2
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_clear_shutdown
}, {
    // emergency_stop
    .encoded_msgid=3, // msgid=3
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_emergency_stop
}, {
    // get_uptime
    .encoded_msgid=4, // msgid=4
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_uptime
}, {
    // get_clock
    .encoded_msgid=5, // msgid=5
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_clock
}, {
    // finalize_config crc=%u
    .encoded_msgid=6, // msgid=6
    .num_params=1,
    .param_types = command_parameters5,
    .num_args=1,
    .flags=0,
    .func=command_finalize_config
}, {
    // get_config
    .encoded_msgid=7, // msgid=7
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_config
}, {
    // allocate_oids count=%c
    .encoded_msgid=8, // msgid=8
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_allocate_oids
}, {
    // debug_nop
    .encoded_msgid=9, // msgid=9
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_debug_nop
}, {
    // debug_ping data=%*s
    .encoded_msgid=10, // msgid=10
    .num_params=1,
    .param_types = command_parameters7,
    .num_args=2,
    .flags=0x01,
    .func=command_debug_ping
}, {
    // debug_write order=%c addr=%u val=%u
    .encoded_msgid=11, // msgid=11
    .num_params=3,
    .param_types = command_parameters24,
    .num_args=3,
    .flags=0x01,
    .func=command_debug_write
}, {
    // debug_read order=%c addr=%u
    .encoded_msgid=12, // msgid=12
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0x01,
    .func=command_debug_read
}, {
    // set_digital_out pin=%u value=%c
    .encoded_msgid=13, // msgid=13
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_set_digital_out
}, {
    // update_digital_out oid=%c value=%c
    .encoded_msgid=14, // msgid=14
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_update_digital_out
}, {
    // queue_digital_out oid=%c clock=%u on_ticks=%u
    .encoded_msgid=15, // msgid=15
    .num_params=3,
    .param_types = command_parameters24,
    .num_args=3,
    .flags=0,
    .func=command_queue_digital_out
}, {
    // set_digital_out_pwm_cycle oid=%c cycle_ticks=%u
    .encoded_msgid=16, // msgid=16
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_set_digital_out_pwm_cycle
}, {
    // config_digital_out oid=%c pin=%u value=%c default_value=%c max_duration=%u
    .encoded_msgid=17, // msgid=17
    .num_params=5,
    .param_types = command_parameters26,
    .num_args=5,
    .flags=0,
    .func=command_config_digital_out
}, {
    // stepper_stop_on_trigger oid=%c trsync_oid=%c
    .encoded_msgid=18, // msgid=18
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_stepper_stop_on_trigger
}, {
    // stepper_get_position oid=%c
    .encoded_msgid=19, // msgid=19
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_stepper_get_position
}, {
    // reset_step_clock oid=%c clock=%u
    .encoded_msgid=20, // msgid=20
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_reset_step_clock
}, {
    // set_next_step_dir oid=%c dir=%c
    .encoded_msgid=21, // msgid=21
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_set_next_step_dir
}, {
    // queue_step oid=%c interval=%u count=%hu add=%hi
    .encoded_msgid=22, // msgid=22
    .num_params=4,
    .param_types = command_parameters27,
    .num_args=4,
    .flags=0,
    .func=command_queue_step
}, {
    // config_stepper oid=%c step_pin=%c dir_pin=%c invert_step=%c step_pulse_ticks=%u
    .encoded_msgid=23, // msgid=23
    .num_params=5,
    .param_types = command_parameters28,
    .num_args=5,
    .flags=0,
    .func=command_config_stepper
}, {
    // endstop_query_state oid=%c
    .encoded_msgid=24, // msgid=24
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_endstop_query_state
}, {
    // endstop_home oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u pin_value=%c trsync_oid=%c trigger_reason=%c
    .encoded_msgid=25, // msgid=25
    .num_params=8,
    .param_types = command_parameters29,
    .num_args=8,
    .flags=0,
    .func=command_endstop_home
}, {
    // config_endstop oid=%c pin=%c pull_up=%c
    .encoded_msgid=26, // msgid=26
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_endstop
}, {
    // trsync_trigger oid=%c reason=%c
    .encoded_msgid=27, // msgid=27
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_trsync_trigger
}, {
    // trsync_set_timeout oid=%c clock=%u
    .encoded_msgid=28, // msgid=28
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_trsync_set_timeout
}, {
    // trsync_start oid=%c report_clock=%u report_ticks=%u expire_reason=%c
    .encoded_msgid=29, // msgid=29
    .num_params=4,
    .param_types = command_parameters16,
    .num_args=4,
    .flags=0,
    .func=command_trsync_start
}, {
    // config_trsync oid=%c
    .encoded_msgid=30, // msgid=30
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_config_trsync
}, {
    // query_analog_in oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u min_value=%hu max_value=%hu range_check_count=%c
    .encoded_msgid=31, // msgid=31
    .num_params=8,
    .param_types = command_parameters31,
    .num_args=8,
    .flags=0,
    .func=command_query_analog_in
}, {
    // config_analog_in oid=%c pin=%u
    .encoded_msgid=32, // msgid=32
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_config_analog_in
}, {
    // config_spi_shutdown oid=%c spi_oid=%c shutdown_msg=%*s
    .encoded_msgid=33, // msgid=33
    .num_params=3,
    .param_types = command_parameters13,
    .num_args=4,
    .flags=0,
    .func=command_config_spi_shutdown
}, {
    // spi_send oid=%c data=%*s
    .encoded_msgid=34, // msgid=34
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_send
}, {
    // spi_transfer oid=%c data=%*s
    .encoded_msgid=35, // msgid=35
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_transfer
}, {
    // spi_set_bus oid=%c spi_bus=%u mode=%u rate=%u
    .encoded_msgid=36, // msgid=36
    .num_params=4,
    .param_types = command_parameters15,
    .num_args=4,
    .flags=0,
    .func=command_spi_set_bus
}, {
    // config_spi_without_cs oid=%c
    .encoded_msgid=37, // msgid=37
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_config_spi_without_cs
}, {
    // config_spi oid=%c pin=%u cs_active_high=%c
    .encoded_msgid=38, // msgid=38
    .num_params=3,
    .param_types = command_parameters32,
    .num_args=3,
    .flags=0,
    .func=command_config_spi
}, {
    // i2c_modify_bits oid=%c reg=%*s clear_set_bits=%*s
    .encoded_msgid=39, // msgid=39
    .num_params=3,
    .param_types = command_parameters33,
    .num_args=5,
    .flags=0,
    .func=command_i2c_modify_bits
}, {
    // i2c_read oid=%c reg=%*s read_len=%u
    .encoded_msgid=40, // msgid=40
    .num_params=3,
    .param_types = command_parameters34,
    .num_args=4,
    .flags=0,
    .func=command_i2c_read
}, {
    // i2c_write oid=%c data=%*s
    .encoded_msgid=41, // msgid=41
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_i2c_write
}, {
    // i2c_set_bus oid=%c i2c_bus=%u rate=%u address=%u
    .encoded_msgid=42, // msgid=42
    .num_params=4,
    .param_types = command_parameters15,
    .num_args=4,
    .flags=0,
    .func=command_i2c_set_bus
}, {
    // config_i2c oid=%c
    .encoded_msgid=43, // msgid=43
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_config_i2c
}, {
    // set_pwm_out pin=%u cycle_ticks=%u value=%hu
    .encoded_msgid=44, // msgid=44
    .num_params=3,
    .param_types = command_parameters35,
    .num_args=3,
    .flags=0,
    .func=command_set_pwm_out
}, {
    // queue_pwm_out oid=%c clock=%u value=%hu
    .encoded_msgid=45, // msgid=45
    .num_params=3,
    .param_types = command_parameters11,
    .num_args=3,
    .flags=0,
    .func=command_queue_pwm_out
}, {
    // config_pwm_out oid=%c pin=%u cycle_ticks=%u value=%hu default_value=%hu max_duration=%u
    .encoded_msgid=46, // msgid=46
    .num_params=6,
    .param_types = command_parameters36,
    .num_args=6,
    .flags=0,
    .func=command_config_pwm_out
}, {
    // buttons_ack oid=%c count=%c
    .encoded_msgid=47, // msgid=47
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_buttons_ack
}, {
    // buttons_query oid=%c clock=%u rest_ticks=%u retransmit_count=%c invert=%c
    .encoded_msgid=48, // msgid=48
    .num_params=5,
    .param_types = command_parameters37,
    .num_args=5,
    .flags=0,
    .func=command_buttons_query
}, {
    // buttons_add oid=%c pos=%c pin=%u pull_up=%c
    .encoded_msgid=49, // msgid=49
    .num_params=4,
    .param_types = command_parameters9,
    .num_args=4,
    .flags=0,
    .func=command_buttons_add
}, {
    // config_buttons oid=%c button_count=%c
    .encoded_msgid=50, // msgid=50
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_config_buttons
}, {
    // tmcuart_send oid=%c write=%*s read=%c
    .encoded_msgid=51, // msgid=51
    .num_params=3,
    .param_types = command_parameters38,
    .num_args=4,
    .flags=0,
    .func=command_tmcuart_send
}, {
    // config_tmcuart oid=%c rx_pin=%u pull_up=%c tx_pin=%u bit_time=%u
    .encoded_msgid=52, // msgid=52
    .num_params=5,
    .param_types = command_parameters39,
    .num_args=5,
    .flags=0,
    .func=command_config_tmcuart
}, {
    // neopixel_send oid=%c
    .encoded_msgid=53, // msgid=53
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_neopixel_send
}, {
    // neopixel_update oid=%c pos=%hu data=%*s
    .encoded_msgid=54, // msgid=54
    .num_params=3,
    .param_types = command_parameters20,
    .num_args=4,
    .flags=0,
    .func=command_neopixel_update
}, {
    // config_neopixel oid=%c pin=%u data_size=%hu bit_max_ticks=%u reset_min_ticks=%u
    .encoded_msgid=55, // msgid=55
    .num_params=5,
    .param_types = command_parameters40,
    .num_args=5,
    .flags=0,
    .func=command_config_neopixel
}, {
    // query_counter oid=%c clock=%u poll_ticks=%u sample_ticks=%u
    .encoded_msgid=56, // msgid=56
    .num_params=4,
    .param_types = command_parameters15,
    .num_args=4,
    .flags=0,
    .func=command_query_counter
}, {
    // config_counter oid=%c pin=%u pull_up=%c
    .encoded_msgid=57, // msgid=57
    .num_params=3,
    .param_types = command_parameters32,
    .num_args=3,
    .flags=0,
    .func=command_config_counter
}, {
    // st7920_send_data oid=%c data=%*s
    .encoded_msgid=58, // msgid=58
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_st7920_send_data
}, {
    // st7920_send_cmds oid=%c cmds=%*s
    .encoded_msgid=59, // msgid=59
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_st7920_send_cmds
}, {
    // config_st7920 oid=%c cs_pin=%u sclk_pin=%u sid_pin=%u sync_delay_ticks=%u cmd_delay_ticks=%u
    .encoded_msgid=60, // msgid=60
    .num_params=6,
    .param_types = command_parameters41,
    .num_args=6,
    .flags=0,
    .func=command_config_st7920
}, {
    // hd44780_send_data oid=%c data=%*s
    .encoded_msgid=61, // msgid=61
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_hd44780_send_data
}, {
    // hd44780_send_cmds oid=%c cmds=%*s
    .encoded_msgid=62, // msgid=62
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_hd44780_send_cmds
}, {
    // config_hd44780 oid=%c rs_pin=%u e_pin=%u d4_pin=%u d5_pin=%u d6_pin=%u d7_pin=%u delay_ticks=%u
    .encoded_msgid=63, // msgid=63
    .num_params=8,
    .param_types = command_parameters42,
    .num_args=8,
    .flags=0,
    .func=command_config_hd44780
}, {
    // spi_set_software_bus oid=%c miso_pin=%u mosi_pin=%u sclk_pin=%u mode=%u rate=%u
    .encoded_msgid=64, // msgid=64
    .num_params=6,
    .param_types = command_parameters41,
    .num_args=6,
    .flags=0,
    .func=command_spi_set_software_bus
}, {
    // i2c_set_software_bus oid=%c scl_pin=%u sda_pin=%u rate=%u address=%u
    .encoded_msgid=65, // msgid=65
    .num_params=5,
    .param_types = command_parameters43,
    .num_args=5,
    .flags=0,
    .func=command_i2c_set_software_bus
}, {
    // query_thermocouple oid=%c clock=%u rest_ticks=%u min_value=%u max_value=%u max_invalid_count=%c
    .encoded_msgid=66, // msgid=66
    .num_params=6,
    .param_types = command_parameters44,
    .num_args=6,
    .flags=0,
    .func=command_query_thermocouple
}, {
    // config_thermocouple oid=%c spi_oid=%c thermocouple_type=%c
    .encoded_msgid=67, // msgid=67
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_thermocouple
}, {
    // query_adxl345_status oid=%c
    .encoded_msgid=68, // msgid=68
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_adxl345_status
}, {
    // query_adxl345 oid=%c rest_ticks=%u
    .encoded_msgid=69, // msgid=69
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_query_adxl345
}, {
    // config_adxl345 oid=%c spi_oid=%c
    .encoded_msgid=70, // msgid=70
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_config_adxl345
}, {
    // spi_angle_transfer oid=%c data=%*s
    .encoded_msgid=71, // msgid=71
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_angle_transfer
}, {
    // query_spi_angle oid=%c clock=%u rest_ticks=%u time_shift=%c
    .encoded_msgid=72, // msgid=72
    .num_params=4,
    .param_types = command_parameters16,
    .num_args=4,
    .flags=0,
    .func=command_query_spi_angle
}, {
    // config_spi_angle oid=%c spi_oid=%c spi_angle_type=%c
    .encoded_msgid=73, // msgid=73
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_spi_angle
}, {
    // query_mpu9250_status oid=%c
    .encoded_msgid=74, // msgid=74
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_mpu9250_status
}, {
    // query_mpu9250 oid=%c rest_ticks=%u
    .encoded_msgid=75, // msgid=75
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_query_mpu9250
}, {
    // config_mpu9250 oid=%c i2c_oid=%c
    .encoded_msgid=76, // msgid=76
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_config_mpu9250
}, {
    // query_lis2dw_status oid=%c
    .encoded_msgid=77, // msgid=77
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_lis2dw_status
}, {
    // query_lis2dw oid=%c rest_ticks=%u
    .encoded_msgid=78, // msgid=78
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_query_lis2dw
}, {
    // config_lis2dw oid=%c spi_oid=%c
    .encoded_msgid=79, // msgid=79
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_config_lis2dw
}, {
    // query_status_ldc1612 oid=%c
    .encoded_msgid=80, // msgid=80
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_status_ldc1612
}, {
    // query_ldc1612 oid=%c rest_ticks=%u
    .encoded_msgid=81, // msgid=81
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_query_ldc1612
}, {
    // query_ldc1612_home_state oid=%c
    .encoded_msgid=82, // msgid=82
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_ldc1612_home_state
}, {
    // ldc1612_setup_home oid=%c clock=%u threshold=%u trsync_oid=%c trigger_reason=%c error_reason=%c
    .encoded_msgid=83, // msgid=83
    .num_params=6,
    .param_types = command_parameters45,
    .num_args=6,
    .flags=0,
    .func=command_ldc1612_setup_home
}, {
    // config_ldc1612_with_intb oid=%c i2c_oid=%c intb_pin=%c
    .encoded_msgid=84, // msgid=84
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_ldc1612_with_intb
}, {
    // config_ldc1612 oid=%c i2c_oid=%c
    .encoded_msgid=85, // msgid=85
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_config_ldc1612
}, {
    // config_reset
    .encoded_msgid=86, // msgid=86
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_config_reset
}, {
    // set_pca9685_out bus=%c addr=%c channel=%c cycle_ticks=%u value=%hu
    .encoded_msgid=87, // msgid=87
    .num_params=5,
    .param_types = command_parameters46,
    .num_args=5,
    .flags=0,
    .func=command_set_pca9685_out
}, {
    // queue_pca9685_out oid=%c clock=%u value=%hu
    .encoded_msgid=88, // msgid=88
    .num_params=3,
    .param_types = command_parameters11,
    .num_args=3,
    .flags=0,
    .func=command_queue_pca9685_out
}, {
    // config_pca9685 oid=%c bus=%c addr=%c channel=%c cycle_ticks=%u value=%hu default_value=%hu max_duration=%u
    .encoded_msgid=89, // msgid=89
    .num_params=8,
    .param_types = command_parameters47,
    .num_args=8,
    .flags=0,
    .func=command_config_pca9685
}, {
    // query_ds18b20 oid=%c clock=%u rest_ticks=%u min_value=%i max_value=%i
    .encoded_msgid=90, // msgid=90
    .num_params=5,
    .param_types = command_parameters48,
    .num_args=5,
    .flags=0,
    .func=command_query_ds18b20
}, {
    // config_ds18b20 oid=%c serial=%*s max_error_count=%c
    .encoded_msgid=91, // msgid=91
    .num_params=3,
    .param_types = command_parameters38,
    .num_args=4,
    .flags=0,
    .func=command_config_ds18b20
},
};

const uint16_t command_index_size PROGMEM = ARRAY_SIZE(command_index);

// version: v0.11.0-562-g6e27ae10-dirty-20240616_164235-utkacraft.ru
// build_versions: gcc: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 binutils: (GNU Binutils for Ubuntu) 2.34

const uint8_t command_identify_data[] PROGMEM = {
    0x78, 0xda, 0xa5, 0x1a, 0xd9, 0x6e, 0xe4, 0x36,
    0xf2, 0x57, 0xb8, 0x0d, 0x0c, 0x72, 0xc0, 0x76,
    0x5a, 0x67, 0xab, 0x0d, 0xe4, 0xc1, 0x71, 0x0e,
    0x0c, 0x12, 0x27, 0x93, 0x78, 0x06, 0xbb, 0xc0,
    0x22, 0x10, 0x64, 0x89, 0xdd, 0x4d, 0x58, 0x57,
    0x44, 0xc9, 0xc7, 0x06, 0xb3, 0xdf, 0xbe, 0x55,
    0x2c, 0x5e, 0x52, 0xb7, 0x3d, 0xd9, 0x5d, 0xbf,
    0xb4, 0xc8, 0xaa, 0x22, 0x8b, 0xc5, 0xba, 0xe9,
    0x3f, 0x57, 0x45, 0xdf, 0xaf, 0x2e, 0x57, 0x3f,
    0xd6, 0xa2, 0xef, 0xf9, 0xb0, 0x3a, 0x5b, 0xdd,
    0x4d, 0xa2, 0xae, 0xf2, 0x07, 0x3e, 0x48, 0xd1,
    0xb5, 0x12, 0x40, 0xfb, 0xb2, 0xbc, 0x64, 0x9f,
    0x7f, 0xb8, 0x9b, 0xda, 0x71, 0x62, 0xdb, 0x8b,
    0xf8, 0x62, 0x7d, 0x1e, 0x4c, 0x6a, 0x14, 0xfc,
    0x3b, 0x5c, 0x5f, 0xac, 0xe3, 0x8b, 0xf0, 0x0b,
    0x9a, 0x67, 0x77, 0xa2, 0x9d, 0x46, 0x51, 0x4b,
    0xc0, 0xff, 0xe1, 0xe7, 0x0f, 0xec, 0x1b, 0x3d,
    0x64, 0xbb, 0x6e, 0x60, 0xb4, 0xc0, 0x17, 0x2c,
    0xbc, 0x88, 0x62, 0xd8, 0xa6, 0xec, 0x9a, 0xa6,
    0x68, 0x2b, 0xd8, 0xe0, 0xcf, 0x55, 0x51, 0xd7,
    0x5d, 0x59, 0x8c, 0x3c, 0xef, 0x44, 0x25, 0x59,
    0xd9, 0x01, 0xe2, 0xd7, 0x6f, 0xca, 0xd5, 0x65,
    0x86, 0xdc, 0x8c, 0x23, 0xb0, 0x91, 0x17, 0xe5,
    0x3d, 0x03, 0x28, 0x4c, 0x7b, 0xf0, 0x78, 0xe3,
    0x21, 0x54, 0x95, 0x41, 0xe8, 0x3b, 0xa9, 0x7e,
    0x44, 0xfb, 0xf5, 0x9b, 0x89, 0xf5, 0x53, 0x5d,
    0xe7, 0x53, 0x4f, 0x04, 0x5b, 0x47, 0xf0, 0xc7,
    0xc4, 0x87, 0x67, 0xbb, 0x26, 0x30, 0x70, 0x8f,
    0xd8, 0x03, 0x97, 0x63, 0x3e, 0x8a, 0xf2, 0x5e,
    0xd2, 0x68, 0x1c, 0x8a, 0x56, 0x36, 0x62, 0xcc,
    0xcd, 0xae, 0x4c, 0xb4, 0x20, 0x1b, 0xbd, 0x3f,
    0x30, 0x58, 0xd6, 0xbc, 0x18, 0x72, 0x79, 0x98,
    0xc6, 0xaa, 0x7b, 0x6c, 0x57, 0x97, 0x21, 0x1e,
    0xad, 0xdd, 0x89, 0x3d, 0x70, 0xf4, 0x54, 0x47,
    0x71, 0x62, 0xb6, 0x90, 0xbd, 0xc8, 0xe9, 0x73,
    0x75, 0xb9, 0x59, 0x3b, 0xac, 0xb6, 0xa8, 0xbb,
    0x7d, 0x2e, 0x5a, 0xcb, 0xbd, 0x62, 0x7b, 0x75,
    0x19, 0xb9, 0x95, 0x34, 0xcb, 0x06, 0x83, 0x86,
    0xb9, 0x93, 0x43, 0xe2, 0x96, 0x53, 0x93, 0x7c,
    0x98, 0x2f, 0x36, 0x93, 0x41, 0xb2, 0xb1, 0xc8,
    0x95, 0xd8, 0x8b, 0xb1, 0xa8, 0xf3, 0x6e, 0x1a,
    0x17, 0x04, 0x0f, 0x45, 0x3d, 0x71, 0x1c, 0x57,
    0x7c, 0x57, 0x4c, 0xf5, 0x98, 0xdb, 0x89, 0xa6,
    0x78, 0xca, 0xab, 0x69, 0x28, 0x46, 0xd0, 0x0e,
    0xc5, 0x67, 0xe0, 0xad, 0x27, 0x83, 0xec, 0x2e,
    0x5c, 0xdb, 0x13, 0xf3, 0x41, 0x14, 0xf5, 0xd7,
    0x6f, 0xbe, 0x94, 0x8a, 0x8a, 0x0f, 0x43, 0x37,
    0x78, 0x5c, 0x6f, 0x03, 0x4b, 0xc8, 0x41, 0x11,
    0xc6, 0xae, 0x9f, 0x31, 0x51, 0xce, 0xb8, 0x0e,
    0x53, 0x8b, 0x7c, 0xa8, 0xe2, 0x78, 0x93, 0xd9,
    0x5d, 0x06, 0x99, 0x6b, 0xa6, 0xb9, 0xf9, 0xa8,
    0x62, 0xfb, 0x95, 0xd8, 0xaf, 0xd4, 0x7e, 0x6d,
    0xec, 0x17, 0xaf, 0x8b, 0x67, 0x7b, 0xdb, 0xab,
    0xcb, 0x34, 0xb2, 0x9b, 0x88, 0xb0, 0x64, 0xe6,
    0xb6, 0x62, 0x37, 0x5d, 0x57, 0x65, 0x90, 0x06,
    0xa1, 0xd9, 0x1b, 0xb0, 0xec, 0x9d, 0x66, 0xc9,
    0x12, 0x2b, 0x7f, 0x14, 0xe3, 0x01, 0x6e, 0x76,
    0xbc, 0x3b, 0xc6, 0x67, 0x38, 0x4d, 0x7c, 0x20,
    0x6d, 0xec, 0x68, 0x85, 0x0c, 0xab, 0xc7, 0x93,
    0x4a, 0xb3, 0xb5, 0x48, 0x4d, 0x3f, 0x6d, 0xc3,
    0x64, 0x7d, 0x8a, 0x8d, 0x8d, 0x13, 0x54, 0xcb,
    0xbb, 0x5e, 0x3c, 0xf1, 0x7a, 0x71, 0xb7, 0x55,
    0x31, 0x16, 0xb9, 0x14, 0xff, 0x82, 0xeb, 0x3c,
    0x4c, 0x60, 0xb2, 0x63, 0x8e, 0xb7, 0xe3, 0xe9,
    0xbc, 0xe4, 0x30, 0x25, 0x5a, 0x4f, 0x30, 0x89,
    0x3b, 0x5b, 0x5f, 0x16, 0xdb, 0x34, 0x4b, 0x9c,
    0x2e, 0x2a, 0x5b, 0x03, 0xeb, 0x1b, 0x94, 0x1d,
    0x1d, 0x8a, 0xb6, 0xe5, 0xb5, 0xfa, 0x7c, 0x06,
    0xd3, 0x70, 0xcb, 0x6a, 0x05, 0x3a, 0x4c, 0x4b,
    0x95, 0x82, 0x99, 0x23, 0x9d, 0xca, 0xdc, 0x51,
    0xfb, 0xc7, 0xe6, 0x84, 0x7e, 0xfe, 0x3f, 0x8b,
    0xc7, 0x4e, 0x42, 0xea, 0xac, 0xb0, 0x9d, 0x9b,
    0x01, 0x81, 0x2f, 0xb7, 0x42, 0xe7, 0x33, 0x8a,
    0x07, 0x9e, 0x1f, 0xc4, 0xfe, 0xa0, 0x64, 0x1c,
    0x65, 0x3e, 0x3e, 0x98, 0xf0, 0xbe, 0xe6, 0xc7,
    0x37, 0xc6, 0x2c, 0x2c, 0x1f, 0x9f, 0x7b, 0x4e,
    0xb7, 0x13, 0xcd, 0x28, 0x8d, 0xdb, 0x38, 0x45,
    0xac, 0x41, 0x79, 0x23, 0xf7, 0x68, 0x42, 0xb0,
    0xeb, 0x9c, 0x16, 0x95, 0x0b, 0x04, 0x93, 0x97,
    0xd2, 0x2a, 0x6a, 0xe4, 0x4c, 0x51, 0x8e, 0x9b,
    0xad, 0xb3, 0xc4, 0xd2, 0xda, 0x88, 0x2c, 0xeb,
    0x7b, 0xfb, 0x2d, 0x2a, 0xfb, 0xf9, 0xdc, 0x96,
    0xf9, 0xdc, 0x1c, 0x58, 0xd9, 0x54, 0xf9, 0x91,
    0x85, 0xac, 0xbd, 0x1d, 0x38, 0x46, 0x0c, 0xcb,
    0x3a, 0x0c, 0xb5, 0x3e, 0xb3, 0x4a, 0x0c, 0xe6,
    0x93, 0xbc, 0xa5, 0x42, 0x76, 0x58, 0x53, 0x2d,
    0xb9, 0xb7, 0x68, 0xe8, 0x0e, 0x36, 0x1e, 0xf8,
    0xd0, 0x74, 0xe0, 0x23, 0xfa, 0x93, 0x12, 0xf5,
    0xc1, 0x4e, 0xa8, 0xa9, 0x3b, 0xf6, 0xd8, 0x94,
    0x53, 0x31, 0x58, 0x6d, 0x19, 0x9e, 0xf2, 0x23,
    0x0f, 0xc8, 0x46, 0x3b, 0x89, 0xba, 0x3f, 0x8a,
    0x86, 0x93, 0x8e, 0x3b, 0x7f, 0x3b, 0x0e, 0x28,
    0x0f, 0x27, 0x56, 0x38, 0x74, 0xc5, 0xef, 0x26,
    0xb0, 0xa8, 0x0e, 0x62, 0xe5, 0xd6, 0x8c, 0x60,
    0x95, 0xbd, 0xb2, 0x26, 0xba, 0x9f, 0xc0, 0xa2,
    0x0d, 0xbc, 0x80, 0x60, 0x34, 0x54, 0x7c, 0x70,
    0xb6, 0x81, 0x9e, 0x32, 0x34, 0x08, 0x8f, 0x83,
    0x18, 0xf9, 0x11, 0x06, 0xaa, 0x31, 0x21, 0x82,
    0x67, 0xe4, 0x0d, 0x1f, 0xf6, 0xbc, 0x2d, 0x9f,
    0x73, 0xf4, 0x8c, 0xc0, 0x04, 0x4c, 0x91, 0x97,
    0xcc, 0x0f, 0x5d, 0xc3, 0x8f, 0x02, 0x97, 0x2c,
    0x9a, 0xde, 0x37, 0x09, 0x3d, 0xb6, 0x61, 0x6b,
    0x1e, 0xd8, 0x80, 0x75, 0xe7, 0xd2, 0xe9, 0xb8,
    0x56, 0xc6, 0x83, 0xd8, 0xef, 0xf9, 0x80, 0x87,
    0x90, 0x1d, 0xb9, 0xa7, 0x30, 0x71, 0x9b, 0xab,
    0xb0, 0x09, 0x3c, 0x15, 0x23, 0xb7, 0x02, 0x0a,
    0xc1, 0x7d, 0xed, 0x04, 0x04, 0x32, 0x70, 0x2a,
    0x39, 0xc9, 0x90, 0x95, 0x43, 0x49, 0x1a, 0x73,
    0xb6, 0xda, 0x83, 0x3f, 0x51, 0x7c, 0x82, 0x90,
    0xf5, 0x48, 0xe1, 0x80, 0x39, 0xd0, 0x70, 0xea,
    0xf1, 0x16, 0xc0, 0x32, 0xcf, 0x56, 0xda, 0xb9,
    0xe7, 0x12, 0xf6, 0xcb, 0x41, 0x03, 0x6d, 0xd0,
    0xc3, 0x6f, 0x92, 0x73, 0x1a, 0x2e, 0xd0, 0xf0,
    0x0a, 0x0c, 0x9a, 0xbb, 0x8e, 0x14, 0x84, 0x88,
    0x8e, 0xb1, 0xe9, 0x2a, 0xb1, 0x7b, 0xce, 0xe1,
    0xae, 0xed, 0x5a, 0x03, 0x57, 0x26, 0xc5, 0x74,
    0xec, 0x06, 0x0e, 0x10, 0xaa, 0xad, 0x6c, 0x4b,
    0x64, 0x74, 0x87, 0x73, 0x7c, 0x9c, 0xcb, 0x6b,
    0xae, 0xdd, 0xc8, 0x9a, 0x10, 0x15, 0xf9, 0x24,
    0x7d, 0x5f, 0xac, 0x9c, 0x22, 0x78, 0x52, 0x90,
    0x11, 0xfe, 0xe2, 0xf5, 0x72, 0x49, 0xba, 0x1e,
    0x87, 0x8e, 0x4a, 0x76, 0xbb, 0xf1, 0xb1, 0x18,
    0xb8, 0x4f, 0x0e, 0xf6, 0x69, 0x6d, 0xb2, 0x2a,
    0xcc, 0xe7, 0xa9, 0x95, 0xd2, 0x84, 0x56, 0xd2,
    0xba, 0xb4, 0x3c, 0x7e, 0x8c, 0xc7, 0xaf, 0x78,
    0x3b, 0xc2, 0xe1, 0x59, 0xb7, 0xdb, 0xc1, 0x86,
    0xca, 0xa8, 0x6d, 0xf8, 0x05, 0xb8, 0x89, 0x53,
    0x00, 0x9b, 0x5e, 0x50, 0xab, 0xf1, 0x00, 0x1b,
    0x1e, 0xba, 0xba, 0x52, 0x83, 0xd7, 0x15, 0x85,
    0x51, 0x84, 0xf7, 0x14, 0x27, 0x03, 0xad, 0x35,
    0x51, 0x48, 0xdd, 0x95, 0x55, 0x99, 0xc4, 0x87,
    0x4c, 0x7d, 0xe5, 0xd4, 0x89, 0xd2, 0xb7, 0xc3,
    0xe4, 0x9d, 0x25, 0x01, 0xc5, 0x20, 0xbd, 0x5b,
    0xe4, 0x54, 0x33, 0xa5, 0x06, 0x91, 0x6c, 0x17,
    0x78, 0x4a, 0x4f, 0x27, 0xe7, 0x20, 0xd3, 0xcc,
    0x22, 0x2c, 0xd3, 0xae, 0xff, 0xd1, 0x90, 0x1a,
    0x67, 0x48, 0x3a, 0xd6, 0xb8, 0x11, 0xa4, 0x8e,
    0x7b, 0x20, 0x3c, 0xf0, 0xf2, 0xde, 0x4b, 0x7b,
    0xa2, 0xc0, 0xf0, 0xb0, 0xc8, 0xd5, 0x2c, 0x07,
    0x7d, 0x07, 0xbe, 0x6a, 0xb9, 0xbf, 0x17, 0x8c,
    0x53, 0xb3, 0xc0, 0x22, 0xdf, 0x7a, 0x21, 0x89,
    0xf5, 0x58, 0x14, 0x3e, 0x87, 0x02, 0x5c, 0xd9,
    0xda, 0x2c, 0xb5, 0x48, 0x6c, 0x16, 0x82, 0xcd,
    0x82, 0x05, 0x9e, 0x52, 0x96, 0x85, 0x17, 0xc8,
    0x42, 0x8b, 0x34, 0xcb, 0x61, 0x16, 0x6b, 0x6d,
    0xb2, 0x39, 0xda, 0xf2, 0x8e, 0x36, 0x1b, 0x03,
    0x5f, 0x64, 0x39, 0xcb, 0x75, 0x92, 0x05, 0xde,
    0xd1, 0x42, 0x56, 0x6b, 0x8e, 0x82, 0xf4, 0x0b,
    0x92, 0x42, 0x2f, 0x04, 0x31, 0x59, 0xec, 0xe8,
    0xa6, 0x36, 0xf6, 0x40, 0xb4, 0xf2, 0x42, 0x48,
    0x70, 0x62, 0x2b, 0xbe, 0x53, 0x71, 0xeb, 0xd3,
    0xd7, 0x31, 0x53, 0x18, 0x1a, 0x40, 0xbc, 0x04,
    0x37, 0x5a, 0x79, 0xfa, 0x92, 0xd2, 0x75, 0x4f,
    0xfc, 0x54, 0xba, 0x6e, 0xf7, 0xe8, 0xfc, 0x74,
    0x2d, 0x48, 0x0c, 0x89, 0xce, 0xd6, 0x4e, 0x92,
    0x58, 0x45, 0x85, 0x83, 0x64, 0x96, 0x60, 0x9e,
    0x6e, 0x9d, 0x42, 0x8e, 0xed, 0xea, 0x18, 0xcd,
    0x99, 0xcb, 0x67, 0xf9, 0x40, 0x01, 0xcc, 0x38,
    0x99, 0x83, 0x72, 0x58, 0xf0, 0x0b, 0x9a, 0x16,
    0x82, 0x2c, 0x29, 0xb3, 0x54, 0x29, 0x80, 0x5a,
    0x77, 0xb9, 0x09, 0x60, 0x81, 0x40, 0x11, 0xc7,
    0x3f, 0xe9, 0xa2, 0x22, 0x81, 0xd3, 0x45, 0x47,
    0x48, 0x8a, 0x6d, 0x95, 0x13, 0xda, 0x35, 0x67,
    0x09, 0x22, 0x10, 0xa5, 0x44, 0xd4, 0xf2, 0x27,
    0xcd, 0x02, 0x24, 0x29, 0xd6, 0x6b, 0x8a, 0x81,
    0xe2, 0x58, 0x40, 0x48, 0xbe, 0xd4, 0xfe, 0xfb,
    0x04, 0x17, 0xc4, 0xb9, 0xd1, 0xeb, 0x68, 0x61,
    0x7e, 0x22, 0x69, 0x05, 0x91, 0x82, 0xaa, 0x7a,
    0xd9, 0x22, 0xd6, 0x9c, 0x3b, 0xe7, 0x18, 0x9c,
    0x23, 0xdc, 0x04, 0x84, 0xe7, 0xb9, 0x52, 0x0f,
    0x1a, 0xc5, 0x06, 0x3a, 0x8b, 0x48, 0x38, 0xa5,
    0x23, 0x12, 0xc4, 0x42, 0xee, 0xc5, 0x13, 0x20,
    0x49, 0x1d, 0xc9, 0xa9, 0x70, 0xd4, 0x08, 0xd9,
    0x99, 0x20, 0xd4, 0x74, 0x52, 0x9c, 0x4a, 0x23,
    0x8f, 0x16, 0x4d, 0x35, 0x1f, 0x2f, 0x9f, 0x23,
    0x02, 0x15, 0xa2, 0x0c, 0xf5, 0xb5, 0x40, 0x9f,
    0x6c, 0xe7, 0x58, 0xa7, 0xe3, 0x7c, 0x92, 0x21,
    0x96, 0xca, 0x45, 0x73, 0x4c, 0x26, 0x20, 0x7c,
    0x08, 0xcc, 0xf5, 0xad, 0x95, 0x06, 0x5b, 0x87,
    0xa0, 0x52, 0x18, 0xb4, 0x15, 0x8a, 0x5d, 0xcc,
    0x86, 0x32, 0x2f, 0xb0, 0x01, 0x05, 0x2c, 0xa9,
    0x33, 0xc9, 0x99, 0xa8, 0x55, 0xa8, 0xb5, 0x99,
    0x00, 0xc5, 0x31, 0xb8, 0x11, 0x4d, 0x8d, 0x32,
    0x44, 0x0f, 0x72, 0xc2, 0x7c, 0x40, 0xb5, 0x32,
    0x87, 0x37, 0xfa, 0x19, 0x2a, 0xef, 0xbb, 0x41,
    0xa7, 0x47, 0xe4, 0x2b, 0xd4, 0xd8, 0x2a, 0x09,
    0x7f, 0xea, 0x05, 0x5c, 0x89, 0x9f, 0x8c, 0x6d,
    0xed, 0x4a, 0x8b, 0x53, 0xf8, 0x48, 0xa0, 0x81,
    0x14, 0x55, 0x4f, 0x79, 0x0d, 0xcf, 0x96, 0xe2,
    0x8f, 0x26, 0xeb, 0xc5, 0x46, 0xcc, 0xd5, 0xb7,
    0xd7, 0xf9, 0xcd, 0xd5, 0x3f, 0x30, 0xb9, 0xd9,
    0xc2, 0x15, 0x5d, 0xff, 0xf4, 0xcb, 0xf5, 0x8f,
    0xf9, 0xf7, 0xbf, 0x7d, 0xf7, 0x2b, 0xf6, 0x18,
    0xe8, 0xef, 0x6c, 0x75, 0x73, 0xfd, 0x61, 0x75,
    0xb9, 0xaa, 0x45, 0x3b, 0x3d, 0xad, 0xce, 0x56,
    0xef, 0xae, 0xaf, 0x94, 0xad, 0x18, 0x32, 0x50,
    0xa8, 0x77, 0x7f, 0xbf, 0xa1, 0x61, 0x14, 0x6e,
    0x30, 0xe2, 0xde, 0xbe, 0xbf, 0x7a, 0x7f, 0x9b,
    0xdf, 0x7e, 0xb8, 0xb9, 0xfd, 0x35, 0xff, 0xe6,
    0xea, 0xf6, 0x3b, 0x4c, 0x28, 0xd3, 0x8f, 0x98,
    0x52, 0x4e, 0x90, 0xe4, 0xaa, 0xc2, 0x4c, 0xb5,
    0x81, 0x74, 0xea, 0xa4, 0x3f, 0x2f, 0xd6, 0xab,
    0xcb, 0x7f, 0xae, 0xcf, 0x82, 0xe4, 0x77, 0x40,
    0x05, 0x55, 0x53, 0x8d, 0x22, 0x15, 0xb5, 0x11,
    0xa0, 0x76, 0xca, 0x7e, 0x87, 0xfc, 0xb1, 0x17,
    0x1d, 0x61, 0x86, 0x99, 0x19, 0x97, 0x07, 0xd1,
    0xaf, 0xbf, 0x7a, 0x09, 0x12, 0x58, 0x08, 0xcc,
    0x2f, 0x60, 0xa1, 0x85, 0x25, 0x50, 0x48, 0xcf,
    0x61, 0x91, 0x85, 0x65, 0xa0, 0xe1, 0x73, 0x58,
    0x6c, 0x61, 0x41, 0x00, 0x85, 0xc4, 0x1c, 0x98,
    0x38, 0x60, 0x1c, 0x2f, 0xb9, 0x49, 0x1d, 0x70,
    0x13, 0x2e, 0xd9, 0xd9, 0x38, 0x56, 0xd7, 0xc1,
    0x92, 0x9f, 0xcc, 0x01, 0xa3, 0xb5, 0x61, 0x08,
    0x5c, 0x0e, 0x9d, 0x1e, 0x3e, 0x10, 0x94, 0x26,
    0x09, 0xd8, 0x78, 0x90, 0x3a, 0x50, 0xe0, 0x81,
    0x80, 0x55, 0x1f, 0x14, 0x7a, 0x20, 0xb8, 0x38,
    0x1f, 0x14, 0x79, 0xa0, 0x2c, 0x9e, 0x81, 0x62,
    0x07, 0x4a, 0x41, 0x3f, 0x7c, 0x50, 0xe2, 0x81,
    0x82, 0x39, 0x1b, 0xa9, 0x07, 0x8a, 0xe6, 0x6c,
    0x6c, 0x3c, 0x50, 0xac, 0xd8, 0xf8, 0x38, 0x73,
    0x8f, 0x50, 0xf7, 0x29, 0x65, 0x08, 0xa2, 0x28,
    0x5a, 0x5d, 0x82, 0x46, 0x16, 0x32, 0x59, 0xc7,
    0x9b, 0x4a, 0xe5, 0xb4, 0x63, 0xcd, 0x93, 0x75,
    0x10, 0xde, 0x81, 0x92, 0x69, 0x2a, 0xad, 0x52,
    0xf0, 0x59, 0xf1, 0x87, 0xb5, 0x51, 0x2b, 0xdc,
    0x8f, 0xa6, 0x02, 0x35, 0x05, 0x2a, 0xe9, 0x4f,
    0x86, 0x6a, 0x32, 0x09, 0x42, 0x7f, 0x32, 0x52,
    0x93, 0x1b, 0x23, 0x1a, 0x9a, 0x8c, 0xd5, 0x64,
    0xb0, 0x0e, 0x63, 0x7f, 0x36, 0xa1, 0xd9, 0x30,
    0x9b, 0x6d, 0x95, 0xd2, 0xac, 0xbd, 0x12, 0x9a,
    0xdd, 0xd0, 0x2c, 0x38, 0x3a, 0x73, 0x56, 0x48,
    0x37, 0x04, 0x3a, 0x8a, 0x01, 0x2a, 0xcc, 0x5c,
    0x54, 0xda, 0x34, 0x99, 0x32, 0xe1, 0x1d, 0xe5,
    0x95, 0xd4, 0x12, 0xbb, 0xaa, 0x6b, 0xa6, 0x2d,
    0xd0, 0x84, 0x26, 0xc9, 0x9a, 0x49, 0x8e, 0xec,
    0x50, 0x3c, 0x70, 0xac, 0x97, 0x31, 0x7f, 0xe4,
    0x7e, 0xe8, 0xa1, 0x76, 0xe1, 0x55, 0x8d, 0x2e,
    0xec, 0x99, 0x99, 0xb2, 0xad, 0xa2, 0xb8, 0x7a,
    0x5d, 0xb4, 0xac, 0xed, 0x46, 0x06, 0xbe, 0x8c,
    0x61, 0x3c, 0x60, 0x70, 0x13, 0x44, 0xcc, 0x14,
    0x31, 0x7b, 0x3c, 0x08, 0xf8, 0x26, 0xd7, 0x22,
    0x59, 0x0f, 0xce, 0x11, 0x58, 0xa4, 0xc0, 0x0d,
    0xb4, 0x9f, 0x8d, 0x18, 0x28, 0x99, 0x14, 0x7b,
    0x58, 0x15, 0x76, 0x2f, 0x46, 0x26, 0x24, 0x2b,
    0xf4, 0x5e, 0xd4, 0x46, 0xa1, 0x72, 0x52, 0x23,
    0x4b, 0x44, 0x45, 0xb7, 0x44, 0x45, 0x2f, 0xcd,
    0xaa, 0x3c, 0x41, 0x25, 0x63, 0xb0, 0x1d, 0x6f,
    0x99, 0xe9, 0x34, 0x58, 0x7a, 0xc8, 0x25, 0xae,
    0xa9, 0x7d, 0xcc, 0xfa, 0x62, 0x90, 0x00, 0x52,
    0x95, 0x87, 0xaa, 0x27, 0x0d, 0x60, 0xe0, 0x90,
    0xa3, 0xc8, 0x51, 0x35, 0x91, 0xaf, 0xbb, 0xa9,
    0xae, 0xe8, 0x5c, 0xca, 0xf7, 0x7e, 0x7b, 0x1b,
    0x64, 0xdf, 0x40, 0xde, 0x8c, 0x6c, 0x01, 0x31,
    0xd6, 0x38, 0x45, 0x45, 0xcd, 0x99, 0xbf, 0x84,
    0xca, 0x3e, 0x07, 0x97, 0x59, 0x41, 0xca, 0x23,
    0xc6, 0x2f, 0x28, 0xcf, 0xfc, 0x8b, 0x64, 0xcd,
    0x34, 0xf2, 0x27, 0x4b, 0x07, 0x62, 0x30, 0x78,
    0xf3, 0x9b, 0xc5, 0xf6, 0xb0, 0x81, 0x40, 0xfc,
    0x91, 0xdd, 0x00, 0x29, 0x4a, 0xa5, 0x45, 0xd3,
    0xd3, 0xd6, 0x8c, 0x4a, 0x66, 0x2c, 0x79, 0xbe,
    0xc3, 0xc3, 0x33, 0x88, 0x7d, 0x23, 0x36, 0x24,
    0x9a, 0x0e, 0xd8, 0xe8, 0x5a, 0xa1, 0xa3, 0x8f,
    0xc6, 0xc3, 0x5c, 0x96, 0xf0, 0x20, 0x32, 0x92,
    0x1b, 0x65, 0x74, 0xea, 0xc4, 0xae, 0x80, 0x63,
    0x5c, 0x61, 0xbe, 0x35, 0x65, 0x1d, 0xdf, 0x77,
    0x43, 0xc9, 0x6d, 0x53, 0x8a, 0xe9, 0xee, 0x3d,
    0xf5, 0x46, 0x7f, 0x78, 0xf7, 0xf6, 0x17, 0x86,
    0x86, 0xcb, 0x40, 0x99, 0x05, 0xa0, 0xa1, 0x1c,
    0x76, 0x90, 0x03, 0x56, 0x54, 0x71, 0xbd, 0xa5,
    0x9c, 0xd6, 0x5b, 0x17, 0xfb, 0xc2, 0x4c, 0x54,
    0x67, 0x98, 0x29, 0x6a, 0xb9, 0x75, 0xa0, 0x4b,
    0xea, 0x9d, 0x40, 0x73, 0x41, 0x9d, 0xcc, 0x57,
    0x48, 0x95, 0x96, 0x23, 0x25, 0xdc, 0xc5, 0x58,
    0x80, 0x40, 0x3e, 0xfb, 0xea, 0x33, 0xaa, 0x1e,
    0x0c, 0x91, 0x69, 0x9b, 0xbb, 0x2e, 0x3e, 0x65,
    0xa6, 0x54, 0x83, 0x19, 0x2c, 0x7b, 0x94, 0xc4,
    0x9f, 0x03, 0x34, 0xd4, 0x2d, 0xb0, 0x1d, 0x48,
    0x6b, 0xa9, 0x45, 0x65, 0x80, 0x4d, 0x07, 0x96,
    0xa5, 0xd5, 0x8b, 0x61, 0x1f, 0x15, 0xc3, 0xa8,
    0x03, 0xdb, 0xae, 0xab, 0xed, 0xb3, 0x52, 0x9a,
    0x75, 0x04, 0xd7, 0x55, 0xaf, 0xdd, 0x3f, 0xf2,
    0x18, 0x00, 0x8b, 0x60, 0xe4, 0xe7, 0xb0, 0x69,
    0x64, 0x66, 0x4d, 0xef, 0x55, 0x5b, 0x3a, 0x03,
    0x69, 0xa9, 0x50, 0x4e, 0x09, 0xe4, 0x12, 0xcb,
    0x80, 0xbc, 0xbd, 0xb1, 0xbb, 0x69, 0xa2, 0x7d,
    0xb8, 0x99, 0xcd, 0xeb, 0x02, 0x49, 0x5d, 0x23,
    0xed, 0x1c, 0x7b, 0x42, 0x9a, 0xd5, 0x37, 0x1e,
    0x0e, 0x76, 0x4b, 0x6e, 0x8a, 0x27, 0xd4, 0xdd,
    0xcc, 0xc8, 0x9b, 0x3a, 0x95, 0x37, 0x5c, 0xca,
    0x62, 0xcf, 0x19, 0x6f, 0x4b, 0xc8, 0x0f, 0x8d,
    0x81, 0x02, 0x2f, 0x37, 0x42, 0x4a, 0x0e, 0x5b,
    0x42, 0x5d, 0x5c, 0x4d, 0x35, 0xea, 0x1b, 0x10,
    0x63, 0x5a, 0xce, 0x74, 0xa6, 0xa2, 0x8c, 0x81,
    0x3f, 0x70, 0xbc, 0x28, 0xcc, 0xc8, 0x5f, 0x26,
    0x38, 0x14, 0x43, 0xa5, 0x3c, 0x94, 0xc6, 0xc6,
    0x46, 0xdd, 0xcb, 0xd8, 0x46, 0x2e, 0x1a, 0x19,
    0x1f, 0x8f, 0x6e, 0xf0, 0x2a, 0x55, 0x2d, 0xc3,
    0xe0, 0x6b, 0xd8, 0xd5, 0xdd, 0x23, 0x55, 0x4f,
    0xbf, 0x71, 0xbd, 0x00, 0x2c, 0x85, 0x06, 0x34,
    0x28, 0x8b, 0x03, 0x6f, 0xda, 0x17, 0xe8, 0x53,
    0xb0, 0x8b, 0x73, 0x6b, 0x11, 0x8e, 0xf8, 0x66,
    0x8f, 0x02, 0xfc, 0x32, 0x7f, 0x2a, 0x39, 0x40,
    0xfd, 0xfe, 0x33, 0x25, 0xa3, 0x8e, 0x72, 0xc6,
    0xd2, 0x2b, 0x54, 0x58, 0x72, 0x79, 0x54, 0xe6,
    0xc4, 0xaf, 0x50, 0x60, 0x96, 0x78, 0xcb, 0x47,
    0x7d, 0x27, 0x8a, 0x6d, 0xc4, 0x10, 0xcd, 0xd4,
    0x98, 0x39, 0x63, 0x0b, 0x78, 0x16, 0x6b, 0xd7,
    0xd8, 0x11, 0x83, 0xc5, 0x94, 0xdf, 0x55, 0xee,
    0xcc, 0x7f, 0xd8, 0xba, 0xd5, 0x8e, 0x78, 0xec,
    0x3a, 0xb6, 0x2b, 0x94, 0x4c, 0x48, 0x1e, 0xd8,
    0x00, 0x7c, 0xef, 0xab, 0x88, 0xf6, 0x7b, 0xaa,
    0x17, 0x4f, 0xfd, 0xf2, 0xf7, 0x4a, 0x8a, 0x48,
    0x09, 0x6e, 0x49, 0x72, 0xd5, 0xd0, 0x7c, 0x0f,
    0x23, 0xd0, 0xfd, 0x67, 0x6c, 0x9a, 0x69, 0xdf,
    0x21, 0xe9, 0x91, 0xce, 0x42, 0x50, 0x63, 0x2d,
    0x04, 0x53, 0xfd, 0x0f, 0x6d, 0x71, 0x87, 0xd1,
    0xa8, 0xd3, 0x8a, 0xac, 0xa4, 0x41, 0x18, 0xd4,
    0xf3, 0x73, 0x08, 0xa0, 0x09, 0x70, 0xb1, 0xb8,
    0x02, 0x24, 0x4c, 0x63, 0x4d, 0x4d, 0x27, 0x07,
    0x56, 0x1e, 0x67, 0xe9, 0xbb, 0xa8, 0x9b, 0xbc,
    0x40, 0x2a, 0xaa, 0xd2, 0x81, 0xd7, 0xc7, 0x60,
    0x1d, 0x0b, 0x6c, 0x24, 0x36, 0xb8, 0x71, 0x76,
    0x84, 0xeb, 0x4e, 0x4a, 0x75, 0xd2, 0x12, 0xec,
    0x73, 0x04, 0xda, 0xcb, 0xa9, 0xcf, 0xb7, 0xc0,
    0x42, 0x45, 0x3b, 0x42, 0x4b, 0x8f, 0xd0, 0x9c,
    0xec, 0xe8, 0xd5, 0xcf, 0x81, 0x55, 0x34, 0x9a,
    0xb1, 0x12, 0xfa, 0x60, 0x0c, 0xbf, 0xb7, 0xef,
    0xde, 0xaa, 0xca, 0x8e, 0xba, 0x6f, 0xc7, 0x30,
    0xd9, 0x73, 0x4c, 0x1a, 0x92, 0x64, 0x09, 0x6c,
    0xbb, 0xf6, 0xfc, 0x0e, 0x23, 0x8f, 0xb2, 0xbd,
    0x05, 0x17, 0x33, 0x26, 0xb5, 0x03, 0x34, 0x52,
    0xd3, 0xfe, 0x2a, 0x99, 0xdd, 0x21, 0x75, 0x37,
    0x71, 0xe9, 0x5e, 0x50, 0x8f, 0x5e, 0xc3, 0x08,
    0x30, 0x3b, 0x03, 0xdc, 0xae, 0x7a, 0x49, 0xce,
    0xcb, 0xc3, 0xd4, 0xde, 0x83, 0xf2, 0x41, 0xaa,
    0x52, 0xd1, 0x03, 0xa5, 0x37, 0x2f, 0x1d, 0x00,
    0xb8, 0x21, 0xaf, 0xa7, 0x83, 0x2c, 0x3a, 0x75,
    0xa8, 0xb6, 0x24, 0x2b, 0x25, 0x53, 0x15, 0x47,
    0xbc, 0x9e, 0x3f, 0x15, 0xc1, 0x79, 0x6a, 0xc8,
    0x63, 0x1e, 0x60, 0x01, 0x62, 0x42, 0xa5, 0x27,
    0xd6, 0x44, 0xb6, 0x47, 0x1d, 0xe7, 0x4b, 0xf6,
    0x0b, 0xe4, 0x43, 0x50, 0xe7, 0xdc, 0x61, 0x99,
    0xb6, 0xc3, 0x17, 0x07, 0xf9, 0x37, 0xaa, 0x06,
    0xd5, 0x5b, 0xb7, 0x4d, 0x8d, 0xf4, 0x0b, 0x78,
    0x45, 0xcf, 0x08, 0x12, 0xfb, 0xb6, 0xe8, 0xe1,
    0xc9, 0xf7, 0x94, 0x00, 0x46, 0x10, 0xd6, 0xd5,
    0x90, 0x94, 0xa9, 0xc7, 0xc9, 0x9f, 0xaf, 0xae,
    0x7f, 0xa4, 0x17, 0x1f, 0xf3, 0xe6, 0xa1, 0xca,
    0x63, 0x34, 0xb0, 0xba, 0x18, 0x30, 0x8b, 0xc0,
    0x76, 0xc0, 0x89, 0x1a, 0x10, 0xad, 0x9a, 0x9c,
    0x3a, 0xbe, 0x20, 0xe9, 0xa4, 0x8a, 0x9c, 0x20,
    0x56, 0xbe, 0x90, 0x7e, 0x1e, 0xbd, 0xb2, 0x60,
    0xfe, 0x09, 0x05, 0x5d, 0x14, 0x64, 0x49, 0xa2,
    0x12, 0x6e, 0x3d, 0x48, 0x55, 0xc6, 0x4d, 0x83,
    0x34, 0x51, 0x2e, 0x02, 0x06, 0x69, 0xba, 0x81,
    0xef, 0xe8, 0x23, 0xac, 0x54, 0xc3, 0xc5, 0xb4,
    0x68, 0xec, 0x2b, 0xfc, 0x77, 0x80, 0x1f, 0xde,
    0xfd, 0xf4, 0x10, 0xad, 0x54, 0x1f, 0x08, 0x92,
    0x18, 0xc9, 0xa5, 0x2b, 0xe9, 0x72, 0xd1, 0xce,
    0xba, 0x89, 0xca, 0x63, 0xe7, 0xa7, 0xba, 0x4f,
    0xe7, 0xe8, 0x6b, 0xcc, 0x1b, 0xfe, 0x8c, 0xa4,
    0xf0, 0xda, 0xac, 0x4c, 0x41, 0xa8, 0x41, 0x70,
    0x8e, 0x41, 0x84, 0x72, 0x21, 0x57, 0x8f, 0x9f,
    0x47, 0xf6, 0xf5, 0x19, 0xfc, 0x84, 0x7e, 0x90,
    0x50, 0x25, 0xbb, 0x7a, 0xb7, 0xc0, 0x39, 0x73,
    0xaf, 0xaa, 0x0f, 0x02, 0xe1, 0x21, 0xb7, 0x6d,
    0x2d, 0x24, 0x57, 0x9a, 0xa1, 0xfa, 0xb7, 0xaf,
    0x31, 0xae, 0x49, 0xf4, 0x47, 0xee, 0xed, 0x8f,
    0x3d, 0x06, 0xf3, 0x5a, 0x24, 0xc1, 0x4b, 0xda,
    0xc7, 0x9f, 0x73, 0x54, 0x0e, 0xdd, 0xd9, 0x35,
    0xb0, 0xd7, 0x84, 0x22, 0xc8, 0xcb, 0xea, 0x55,
    0x43, 0xf7, 0x52, 0x33, 0x63, 0xeb, 0xd0, 0x35,
    0x60, 0x8f, 0xc7, 0x8b, 0xf8, 0x0f, 0x41, 0xb8,
    0x77, 0xea, 0x5e, 0x3f, 0x72, 0x73, 0x4f, 0x5e,
    0x03, 0x56, 0x8d, 0x8d, 0x58, 0x43, 0xf7, 0xc2,
    0xe0, 0xe1, 0xda, 0xa7, 0x06, 0x6a, 0xd1, 0x5c,
    0x20, 0x2e, 0x3e, 0x95, 0x38, 0x81, 0xb2, 0x65,
    0x7d, 0x43, 0x32, 0xdd, 0x46, 0xee, 0x45, 0xe2,
    0xa8, 0xbd, 0xec, 0x1d, 0xc0, 0xbc, 0x3b, 0xf8,
    0xc2, 0x4c, 0xbc, 0xd7, 0x84, 0xb9, 0xcc, 0xe4,
    0x54, 0x96, 0xea, 0xc9, 0x04, 0x8f, 0x87, 0xd1,
    0x17, 0xd8, 0xf4, 0x5f, 0xed, 0xce, 0x31, 0x52,
    0x92, 0xfd, 0x43, 0xa5, 0x58, 0xdf, 0xcf, 0xba,
    0x4c, 0x12, 0xb3, 0xbc, 0xb6, 0xe4, 0x8b, 0xf7,
    0x88, 0x73, 0x6a, 0x41, 0x3a, 0x9a, 0x59, 0xe7,
    0xd9, 0x35, 0x4d, 0x75, 0x6f, 0xd8, 0xf4, 0x72,
    0xa8, 0xf7, 0xe8, 0x2f, 0x79, 0x37, 0xed, 0x76,
    0x1c, 0xe2, 0x2d, 0x75, 0xfd, 0xa1, 0x18, 0x02,
    0xa7, 0x92, 0x9b, 0x4c, 0x44, 0x6a, 0x55, 0xc3,
    0xe4, 0xd2, 0x25, 0xde, 0xf6, 0x99, 0xe2, 0xb4,
    0x0c, 0x4f, 0x36, 0x12, 0x8f, 0x6e, 0xd2, 0x6f,
    0x4d, 0xfb, 0x57, 0x1a, 0xa4, 0xf3, 0xce, 0xdd,
    0x27, 0x55, 0x20, 0x52, 0xc5, 0xea, 0x30, 0xaa,
    0x84, 0x1d, 0xea, 0x57, 0x55, 0xba, 0x4a, 0xa7,
    0xf6, 0x72, 0x6a, 0xf4, 0x8f, 0xfc, 0x43, 0x5d,
    0xd5, 0x36, 0x71, 0xcd, 0xb8, 0x45, 0xa7, 0x8e,
    0x1e, 0x7e, 0x04, 0x2e, 0xbb, 0x59, 0x38, 0xa1,
    0xbf, 0x60, 0x06, 0x93, 0x31, 0x03, 0x75, 0xcf,
    0xce, 0x2d, 0x9e, 0x38, 0x02, 0xb6, 0xee, 0x88,
    0xfd, 0xb5, 0xdf, 0x94, 0x73, 0xba, 0x56, 0x16,
    0xb6, 0x43, 0x78, 0xfa, 0xa1, 0xcb, 0x53, 0x3d,
    0x2c, 0x66, 0xe9, 0xfd, 0x92, 0xd1, 0xff, 0x07,
    0x4c, 0x33, 0x2f, 0x83, 0x4d, 0x08, 0xfd, 0xbf,
    0x54, 0xe0, 0x05, 0x1f, 0xd6, 0x17, 0x41, 0x70,
    0xb1, 0x3e, 0x4f, 0xd2, 0xf0, 0x7c, 0x9f, 0xf2,
    0x70, 0x53, 0xf0, 0x60, 0x7d, 0x5e, 0x89, 0x61,
    0x7c, 0x06, 0x66, 0xc2, 0x78, 0x9d, 0x06, 0x69,
    0x1e, 0xa4, 0x71, 0x18, 0x25, 0xe7, 0xd3, 0x78,
    0x5f, 0x94, 0x43, 0xb1, 0x1b, 0x2f, 0x86, 0x69,
    0xf5, 0xf1, 0x3f, 0x98, 0x36, 0x85, 0xd7,
};

// Identify size = 3279 (9640 uncompressed)
const uint32_t command_identify_size PROGMEM
    = ARRAY_SIZE(command_identify_data);
